name: 'Playwright Setup'
description: 'Setup Playwright with browser caching'

inputs:
  browsers:
    description: 'Browsers to install (e.g., chromium, firefox, webkit)'
    required: false
    default: 'chromium'

runs:
  using: 'composite'
  steps:
    - name: Get Playwright version
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(pnpm list @playwright/test --json 2>/dev/null | jq -r '.[0].dependencies["@playwright/test"].version // empty' || echo "")
        if [ -z "$PLAYWRIGHT_VERSION" ]; then
          PLAYWRIGHT_VERSION=$(pnpm list @playwright/test --depth=0 2>/dev/null | grep @playwright/test | awk '{print $2}' || echo "unknown")
        fi
        echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}-${{ inputs.browsers }}

    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm exec playwright install --with-deps ${{ inputs.browsers }}

    - name: Install Playwright system dependencies (cache hit)
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
      run: pnpm exec playwright install-deps ${{ inputs.browsers }}
